### ISSUE TITLE
How to build the Hardware interface module? 

### ISSUE THREAD

**Issue by treefrog911** [jkua/wheelwriter-interface#1]
Would love to try this project on my Wheelwriter but I can't find any info at all on the actual hardware required to interface the Pi to the Wheelwriter (the "Hardware interface module"). Can you help?

**Comment by jkua** [comment]
Hi! Sorry, my work on this is quite intermittent. If you're still interested, I added schematics for the [hardware interface module here](https://github.com/jkua/wheelwriter-interface/tree/main/pcb). v1 is what I've been using.
